services:
  - type: web
    name: flask-stock-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn combined_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
